import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use — BRIDGE',
  description:
    'BRIDGE terms of use. Understand the educational nature of the platform, intellectual property, and limitations of liability.',
};

export default function TermsPage() {
  return (
    <section className="py-16 md:py-24 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="font-serif text-3xl md:text-4xl font-bold text-primary mb-4">
          Terms of Use
        </h1>
        <p className="text-muted text-sm mb-12">Last updated: March 2026</p>

        <div className="space-y-10">
          {/* 1. Nature of Service */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              1. Nature of the Service
            </h2>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              BRIDGE is an educational and guidance platform designed to help
              individuals understand how to partner effectively with AI systems.
              The Partnership Profiles, session plans, and recommendations
              generated by BRIDGE are intended as guidance and inspiration.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              BRIDGE is not a software development service, consulting firm, or
              employment agency. The profiles generated are starting points for
              your journey, not guarantees of any specific outcome.
            </p>
          </div>

          {/* 2. No Guarantee */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              2. No Guarantee of Success
            </h2>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              While BRIDGE is built on the principles proven by real
              partnerships (including EZRE OS), individual results will vary.
              Success depends on your effort, consistency, the quality of your
              AI interactions, and many factors beyond our control.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              We make no promises about the viability, profitability, or
              completeness of anything you build using guidance from BRIDGE.
            </p>
          </div>

          {/* 3. AI-Generated Content */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              3. AI-Generated Content
            </h2>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              Partnership Profiles are generated using AI (Anthropic Claude).
              While we strive for accuracy and helpfulness, AI-generated content
              may contain errors, inaccuracies, or suggestions that are not
              appropriate for your specific situation.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              You are responsible for evaluating and applying any guidance
              provided by BRIDGE or your AI partner. Use your own judgment in
              all decisions related to your projects.
            </p>
          </div>

          {/* 4. Intellectual Property */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              4. Intellectual Property
            </h2>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              <span className="font-medium text-primary">Your content:</span>{' '}
              You retain all rights to the dreams, ideas, and descriptions you
              provide during the assessment. BRIDGE does not claim ownership of
              your input or the projects you build.
            </p>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              <span className="font-medium text-primary">
                Generated profiles:
              </span>{' '}
              Your Partnership Profile is yours to use, share, and build upon.
              You may share it publicly, paste it into AI conversations, and
              adapt it however you see fit.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              <span className="font-medium text-primary">
                BRIDGE platform:
              </span>{' '}
              The BRIDGE name, design, methodology, and platform code are the
              property of Vilmure Ventures. You may not copy, reproduce, or
              redistribute the BRIDGE platform itself.
            </p>
          </div>

          {/* 5. Acceptable Use */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              5. Acceptable Use
            </h2>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              You agree to use BRIDGE in good faith and for lawful purposes. You
              may not:
            </p>
            <ul className="space-y-2 ml-4">
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-border mt-2 flex-shrink-0" />
                <p className="text-secondary text-sm leading-relaxed">
                  Use BRIDGE to generate content that is harmful, illegal, or
                  deceptive.
                </p>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-border mt-2 flex-shrink-0" />
                <p className="text-secondary text-sm leading-relaxed">
                  Attempt to overwhelm or abuse the assessment API.
                </p>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-border mt-2 flex-shrink-0" />
                <p className="text-secondary text-sm leading-relaxed">
                  Misrepresent BRIDGE-generated profiles as professional
                  certifications or credentials.
                </p>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-border mt-2 flex-shrink-0" />
                <p className="text-secondary text-sm leading-relaxed">
                  Scrape, reverse-engineer, or systematically extract data from
                  the platform.
                </p>
              </li>
            </ul>
          </div>

          {/* 6. Limitation of Liability */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              6. Limitation of Liability
            </h2>
            <p className="text-secondary text-sm leading-relaxed mb-3">
              BRIDGE is provided &ldquo;as is&rdquo; without warranties of any
              kind, either express or implied. To the fullest extent permitted
              by law, Vilmure Ventures shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising
              from your use of BRIDGE.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              Our total liability for any claim arising from or related to
              BRIDGE shall not exceed the amount you paid to use the service
              (which, for the free assessment, is $0).
            </p>
          </div>

          {/* 7. Third-Party Services */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              7. Third-Party Services
            </h2>
            <p className="text-secondary text-sm leading-relaxed">
              BRIDGE may recommend third-party AI services (such as Claude by
              Anthropic or ChatGPT by OpenAI). Your use of those services is
              governed by their respective terms and privacy policies. BRIDGE is
              not responsible for the availability, accuracy, or policies of
              third-party services.
            </p>
          </div>

          {/* 8. Changes */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              8. Changes to These Terms
            </h2>
            <p className="text-secondary text-sm leading-relaxed">
              We may update these terms from time to time. If we make
              significant changes, we will indicate this by updating the
              &ldquo;Last updated&rdquo; date above. Your continued use of
              BRIDGE after any changes constitutes acceptance of the revised
              terms.
            </p>
          </div>

          {/* 9. Contact */}
          <div>
            <h2 className="font-serif text-xl font-semibold text-primary mb-4">
              9. Contact
            </h2>
            <p className="text-secondary text-sm leading-relaxed">
              Questions about these terms? Reach us at{' '}
              <a
                href="mailto:legal@bridge-platform.com"
                className="text-bridge-gold hover:text-bridge-gold-dark underline underline-offset-2 transition-colors duration-200"
              >
                legal@bridge-platform.com
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
